// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApX4yCYZYi26L0ekTzu1xr_pItluIZm7w',
    appId: '1:3596106660:web:357d1df6e56ac3eec99f31',
    messagingSenderId: '3596106660',
    projectId: 'connect-hub-social',
    authDomain: 'connect-hub-social.firebaseapp.com',
    storageBucket: 'connect-hub-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGOb3WahU7Wq6X12znSuMMiPoG9__BmIY',
    appId: '1:3596106660:android:f7b4282415f6307ec99f31',
    messagingSenderId: '3596106660',
    projectId: 'connect-hub-social',
    storageBucket: 'connect-hub-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyG0sWMaJNdGcG7tUUPiM-gezX6lkNbWA',
    appId: '1:3596106660:ios:6a95c4d04445634ec99f31',
    messagingSenderId: '3596106660',
    projectId: 'connect-hub-social',
    storageBucket: 'connect-hub-social.appspot.com',
    iosBundleId: 'com.example.connecthubSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyG0sWMaJNdGcG7tUUPiM-gezX6lkNbWA',
    appId: '1:3596106660:ios:6a95c4d04445634ec99f31',
    messagingSenderId: '3596106660',
    projectId: 'connect-hub-social',
    storageBucket: 'connect-hub-social.appspot.com',
    iosBundleId: 'com.example.connecthubSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApX4yCYZYi26L0ekTzu1xr_pItluIZm7w',
    appId: '1:3596106660:web:7e09af639a6716c3c99f31',
    messagingSenderId: '3596106660',
    projectId: 'connect-hub-social',
    authDomain: 'connect-hub-social.firebaseapp.com',
    storageBucket: 'connect-hub-social.appspot.com',
  );
}
